---
title: "Package Release"
# Repo here: https://github.com/rjake/pkg_monitor
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    theme: lumen
    vertical_layout: fill
runtime: shiny
---

```{css css_style}
.body {
  font-size: 10;
  line-height: 1;
  padding-top: 30px !important;
}

.btn {
  padding: 4px 10px 4px;
  font-size: 10px;
}

.form-group {
  margin-top: 10px;
}

label {
  margin-bottom: 0px;
}
```

```{css eval=FALSE}
.navbar-nav > li > a, .navbar-brand {
  padding-top: 4px !important; 
  padding-bottom: 0 !important;
  height: 25px;
}

.navbar {
  min-height:25px !important;
}

.section.sidebar {
  top: 30px;
}

```


```{r dummy_input, eval=interactive()}
input <- list(
  pkg = c("simplecolors", "shinyobjects", "headliner"),
  x = "Today",
  y = "Cummulative",
  n = c(0, 90),
  period = "month",
  full_period = "all"
)

shiny::reactiveConsole(TRUE)
```

```{r setup, include=FALSE}
library(shiny)
library(shinyWidgets)
library(tidyverse)
library(lubridate)
library(simplecolors)
library(glue)
library(DT)
library(plotly)
library(cranlogs)

pkgs <- read_csv(
  #"data/pkg_data.csv"
  "https://raw.githubusercontent.com/rjake/pkg_monitor/master/data/pkg_data.csv"
) |> 
  mutate(
    link = glue("https://rjake.github.io/{package}"),
    png = glue(
      "https://raw.githubusercontent.com/rjake/{package}\\
      /main/pkgdown/favicon/apple-touch-icon-120x120.png"
    )
  ) |> 
  arrange(package)

pkg_colors <- 
  setNames(
    object = sc(pkgs$color), 
    nm = pkgs$package
  )

raw_logs <-
  map2_dfr(
    .x = pkgs$package,
    .y = pkgs$released,
    .f = 
      ~cranlogs::cran_downloads(
        packages = .x,
        from = .y,
        to = today() - 1
      )  
  )

logs <- 
  raw_logs %>%
  group_by(package) %>% 
  filter(count > 0) %>% 
  ungroup()

max_30_day <- function(x) {
  ceiling(x / 30) * 30
}

show_trend <- function(df) {
  count_ts <- ts(df$count, frequency = 7)
  stl <- tryCatch(
    as.data.frame(stl(count_ts, "periodic")$time.series),
    error = function(e) data.frame(trend = df$count, remainder = 0)
  )

  df$trend <- stl$trend
  df$remainder <- stl$remainder
  df
}
```

Sidebar {.sidebar data-width=275}
-----------------------------------------------------------------------

```{r input_pkg}
checkboxGroupButtons(
  inputId = "pkg",
  label = NULL,
  choices = pkgs$package,
  selected = pkgs$package,
)
```

```{r input_y}
radioGroupButtons(
  inputId = "y",
  label = NULL,
  choices = c("Count", "Cummulative")
)
```

```{r input_geom, eval=FALSE}
radioGroupButtons(
  inputId = "geom",
  label = "Line Type",
  choices = c("Line", "Smooth")
)
```


```{r input_period}
radioGroupButtons(
  inputId = "period",
  label = NULL,
  choices = c("day", "week", "month"),
  selected = "week"
) 
```

```{r input_full_period}
radioGroupButtons(
  inputId = "full_period",
  label = NULL,
  choices = c("completed", "all"),
  selected = "all"
)
```

```{r input_x}
radioGroupButtons(
  inputId = "x",
  "Distance From:",
  choices = c("Today", "Inception")
)
```

```{r input_n}
n_days <- max_30_day(as.integer(max(logs$date) - min(logs$date)))
    
sliderInput(
  inputId = "n",
  label = "# Days",
  min = 0,
  max = n_days,
  value = c(0, 60)
)
```

##### About 
```{r hex_stickers}
add_image <- function(i) {
  tags$a(
    href = pkgs$link[i],
    tags$img(
      src = pkgs$png[i],
      title = pkgs$description[i],
      height = "70",
      width =  "70"
    )
  )
}

splitLayout(
  style = "height: 50px;",
  add_image(1),
  add_image(2),
  add_image(3)
)
```

```{r df_reactive}
df_reactive <- reactive({
  if (
    input$period == "day"
    | input$full_period == "all"
    | max(logs$date) == max(ceiling_date(logs$date, input$period))
  ) {
    max_date <- max(logs$date)
  } else {
    max_date <- floor_date(max(logs$date), input$period) - 1
  }
  
  
  logs %>%
    filter(
      date <= max_date,
      package %in% input$pkg
    ) %>%
    mutate(date = floor_date(date, input$period)) %>% 
    count(package, date, wt = count, name = "count") %>%
    group_by(package) %>% 
    mutate(
      cummulative = cumsum(count),
      from_start = as.integer(date - min(date)),
      from_today = as.integer(today() - date) 
    ) %>% 
    ungroup() %>% 
    mutate(y = get(tolower(input$y)))
})
```


Column {.tabset}
-----------------------------------------------------------------------
### Plot
```{r plot}
# plot_data----
plot_data <- reactive({
  if (input$x == "Inception") {
    df <-
      df_reactive() %>% 
      mutate(x = from_start) %>% 
      filter(between(x, min(input$n), max(input$n)))
  } else {
    df <-
      df_reactive() %>% 
      mutate(x = date) %>% 
      filter(between(from_today, min(input$n), max(input$n)))
  }

  df %>% 
    group_by(package) %>% 
    group_modify(~show_trend(.))
})


renderPlotly({
  # title ----
  pkg_deets <-
    df_reactive() %>% 
    group_by(package) %>% 
    summarise(
      #min_date = format(min(date), format = "%m-%d-%Y"),
      #min_n = ifelse(min(from_start) == 0, 0, min(cummulative)),
      #delta = max_n - min_n,
      max_n = 
        max(cummulative) |> 
        scales::number(
          accuracy = 0.1,
          scale_cut = scales::cut_long_scale()
        ) |> 
        str_remove("\\.0$")
    ) %>% 
    ungroup() %>% 
    arrange(package) %>% 
    mutate(
      sentence = glue(
        "{package} ({max_n})"
      )
    ) %>% 
    pull(sentence) %>% 
    glue_collapse(" - ") #|> print()
  
  # subtitle ----
  date_range <-
    range(df_reactive()$date) %>% 
    format(format = "%b %e, %Y") %>%
    str_replace("  ", " ") %>% 
    paste(collapse = " to ")
  
  # plot ----
  p <-
    ggplot(plot_data(), aes(x, y, color = package)) +
      scale_color_manual(values = pkg_colors) +
      ylim(0, NA) +
      theme_minimal() +
      theme(
        panel.grid = element_blank()
      ) +
      labs(
        title = pkg_deets,
        subtitle = date_range,
        x = paste("Distance from", input$x),
        y = input$y
      )
  #print(input$period)
  if (input$period == "day" && input$y == "Count") {
    p <- 
      p + 
      geom_linerange(
        aes(ymin = trend, ymax = trend + remainder), 
        alpha = 0.5
      ) +
      geom_point(aes(y = trend + remainder), alpha = 0.5, size = 0.8) +
      geom_line(aes(y = trend), size = 1)
  } else {
    p <- 
      p + 
      geom_line() +
      geom_point()
  }
  
  ggplotly(p) %>% 
    layout(
      hovermode = "x unified",
      showLegend = TRUE
    )
})
```

### Table
```{r}
renderDT({
  df_reactive() %>%
    select(-c(cummulative:y)) %>%
    #mutate(package = as.factor(package)) %>%
    spread(package, count) %>% 
    arrange(desc(date)) %>%
    datatable(
      extensions = c("FixedHeader", "Scroller"),
      filter = "top",
      rownames = FALSE,
      escape = FALSE,
      options =
        list(
          dom = "Bfrtip",
          deferRender = FALSE,
          scrollY = 540,
          scroller = TRUE,
          scrollX = TRUE,
          fixedHeader = FALSE,
          pageLength = nrow(df_reactive()),
          lengthChange = FALSE
        )
    )
})
```

